# Generated by Django 5.2.6 on 2025-09-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_url', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
