# Generated by Django 5.2.6 on 2025-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_url',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='image_file',
            field=models.FileField(default='', upload_to='image/'),
        ),
    ]
